const API_BASE = 'http://localhost:5000/api';

async function request(url, options = {}) {
  const headers = {
    'Content-Type': 'application/json',
    Authorization: 'Bearer demo_user_token_golden',
    ...(options.headers || {}),
  };
  const res = await fetch(`${API_BASE}${url}`, {
    ...options,
    headers,
  });
  const data = await res.json();
  if (!res.ok) {
    throw new Error(data.error || `HTTP ${res.status}`);
  }
  return data;
}

async function runGoldenDemo() {
  console.log('========================================');
  console.log('🚀 ACCORDVOICE GOLDEN DEMO PIPELINE TEST');
  console.log('========================================\n');

  try {
    // 1. Create Conversation
    console.log('1. Creating new conversation...');
    const convRes = await request('/conversations', {
      method: 'POST',
      body: JSON.stringify({
        title: 'Q3 Product Delivery & Schedule Agreement',
        category: 'Business & Commercial',
        description: 'Negotiating volume delivery schedule',
        participantAName: 'Alice',
        participantBName: 'Bob',
        participantALanguage: 'en',
        participantBLanguage: 'en',
        agreementFields: ['Quantity', 'Delivery Date', 'Responsible Party'],
      }),
    });
    const conv = convRes.conversation || convRes;
    console.log(`✓ Conversation Created: "${conv.title}" (ID: ${conv.id})`);
    console.log(`  Initial State: ${conv.state}\n`);

    // 2. Participant A speaks
    console.log('2. Participant A (Alice) speaks: "I will deliver 50 units on Friday."');
    const turn1Res = await request(`/conversations/${conv.id}/turns`, {
      method: 'POST',
      body: JSON.stringify({
        speaker: 'participant_a',
        originalText: 'I will deliver 50 units on Friday.',
        language: 'en',
      }),
    });
    const turn1 = turn1Res.turn || turn1Res;
    console.log(`✓ Turn 1 Saved: [${turn1.speaker}] "${turn1.original_text}"\n`);

    // 3. Participant B speaks
    console.log('3. Participant B (Bob) speaks: "We agreed on 20 units on Monday."');
    const turn2Res = await request(`/conversations/${conv.id}/turns`, {
      method: 'POST',
      body: JSON.stringify({
        speaker: 'participant_b',
        originalText: 'We agreed on 20 units on Monday.',
        language: 'en',
      }),
    });
    const turn2 = turn2Res.turn || turn2Res;
    console.log(`✓ Turn 2 Saved: [${turn2.speaker}] "${turn2.original_text}"\n`);

    // 4. Run AI Mediation Analysis
    console.log('4. Running AI Mediation Analysis (Gemini 2.0)...');
    const analysisRes = await request(`/conversations/${conv.id}/analysis`, {
      method: 'POST',
      body: JSON.stringify({}),
    });
    console.log(`✓ AI Analysis Completed:`);
    console.log(`  - New State: ${analysisRes.conversationState || analysisRes.state}`);
    console.log(`  - Claims Extracted: ${analysisRes.claims?.length || 0}`);
    if (analysisRes.claims) {
      analysisRes.claims.forEach((c) =>
        console.log(`    • [${c.speaker}] ${c.subject}.${c.attribute}: ${c.value_json?.value || c.value} ${c.unit || ''}`)
      );
    }
    console.log(`  - Conflicts Detected: ${analysisRes.conflicts?.length || 0}`);
    if (analysisRes.conflicts) {
      analysisRes.conflicts.forEach((c) =>
        console.log(`    ⚠️ ${c.conflict_type}: ${c.description}`)
      );
    }
    console.log();

    // 5. Fetch Clarifications generated by AI
    console.log('5. Resolving Clarifications with neutral mutual input...');
    const clarifRes = await request(`/conversations/${conv.id}/clarifications`);
    const clarifs = clarifRes.clarifications || clarifRes || [];
    console.log(`Found ${clarifs.length} clarification items to resolve.`);

    for (const cl of clarifs) {
      if (cl.status === 'pending') {
        console.log(`  - Answering Question: "${cl.question}" -> "50 units on Monday"`);
        await request(`/conversations/${conv.id}/clarifications/${cl.id}/resolve`, {
          method: 'POST',
          body: JSON.stringify({
            answer: '50 units on Monday',
            speaker: 'participant_a',
          }),
        });
      }
    }
    console.log(`✓ All Clarifications Answered & Conflicts Resolved.\n`);

    // 6. Draft Proposed Mutual Agreement
    console.log('6. Drafting Proposed Mutual Agreement...');
    const agrRes = await request(`/conversations/${conv.id}/agreements`, {
      method: 'POST',
      body: JSON.stringify({}),
    });
    const agreement = agrRes.agreement || agrRes;
    console.log(`✓ Agreement Drafted (ID: ${agreement.id}):`);
    console.log(`  Summary: "${agreement.summary}"`);
    console.log(`  Status: ${agreement.status}\n`);

    // 7. Participant A Confirms
    console.log('7. Participant A (Alice) confirms agreement...');
    const confARes = await request(`/conversations/${conv.id}/agreements/${agreement.id}/confirm`, {
      method: 'POST',
      body: JSON.stringify({ participant: 'participant_a' }),
    });
    const agrA = confARes.agreement || confARes;
    console.log(`✓ Party A Confirmed: Status = ${agrA.status} (1 of 2 confirmed)\n`);

    // 8. Participant B Confirms
    console.log('8. Participant B (Bob) confirms agreement...');
    const confBRes = await request(`/conversations/${conv.id}/agreements/${agreement.id}/confirm`, {
      method: 'POST',
      body: JSON.stringify({ participant: 'participant_b' }),
    });
    const agrB = confBRes.agreement || confBRes;
    const convFinal = confBRes.conversation || confBRes;
    console.log(`✓ Party B Confirmed: Status = ${agrB.status} (2 of 2 confirmed)`);
    console.log(`✓ Final Conversation State: ${convFinal.state || 'VERIFIED'}\n`);

    console.log('========================================');
    console.log('🎉 GOLDEN DEMO PIPELINE FULLY VERIFIED!');
    console.log('========================================');
  } catch (err) {
    console.error('❌ Golden Demo Error:', err.message);
  }
}

runGoldenDemo();
